### ISSUE TITLE
请问是否有vue相关的demo示例呢

### ISSUE THREAD

**Issue by UoUoio** [tjt740/threejs-study#5]

**Comment by tjt740** [comment]
你好，我这边没有 vue相关的demo ，这只是react的。最新的代码可以拉去 最新的分支 （master分支有时会忘记合并）

**Comment by tjt740** [comment]
你好，我这边没有 vue相关的demo ，这只是react的。最新的代码可以拉去 最新的分支 （master分支有时会忘记合并）x

**Comment by UoUoio** [comment]
感谢您的回复

  -是的 我有看到分支里有最新的代码, 由于我是后端开发者对于前端框架也仅限于vue,同时也是第一次接触和学习three.js所以看起来有些吃力...就想问一下有没有vue的demo来着

**Comment by UoUoio** [comment]
您好,想问下你的子箱子的position是怎么计算的呢,有没有一些示例或者参考文档,谢谢
